### ISSUE TITLE
Create Date Page

### ISSUE THREAD

**Issue by zoewyon** [zoewyon/clim8#2]
Create view 2 from req. spec.

**Comment by jscherrer123** [comment]
Features:
• Heading: "Step 2. Choose date..."
• Choose date (prio 1 - calendar, prio 2 - manually type in)
• Text: "... and number of passengers"
• Choose number of Adults
• Choose number of Children
• Button with text "NEXT", takes you to Search Result Page

Left side of page:
• Button with text "SIGN IN"
• Button with text "ABOUT"

**Comment by jscherrer123** [comment]
fkn done
