### ISSUE TITLE
Create acceptance page

### ISSUE THREAD

**Issue by zoewyon** [zoewyon/clim8#5]
Create view 5b according to req. spec

**Comment by jscherrer123** [comment]
Done after review

**Comment by zoewyon** [comment]
To be done: Change xxx CO2 to actual value namely change the picture.

**Comment by zoewyon** [comment]
Value changed for Romme.

To be done: acceptance modals for rest of transportations and destinations.

**Comment by zoewyon** [comment]
Acceptance pages done for prototype version.
